ktor:
    application:
        modules:
            - com.yaroslavzghoba.ApplicationKt.module
    deployment:
        port: 8080

database:
    url: "jdbc:postgresql://localhost:5432/railways"
    user: "postgres"
    password: $RAILWAYS_DATABASE_PASSWORD