ktor:
    application:
        modules:
            - com.yaroslavzghoba.ApplicationKt.module
    deployment:
        port: 8080

database:
    url: "jdbc:postgresql://localhost:5432/bookstore"
    user: "postgres"
    password: $BOOKSTORE_DATABASE_PASSWORD